### ISSUE TITLE
`get()` method only returns the default value for each key and ignores conditions

### ISSUE THREAD

**Issue by Bradleycorn** [Inpassor/ts-firebase-config#4]
My firebase Remote Config is setup with various Conditions, and several of my keys use the conditions to set different values when different conditions apply. 

Using this library, when I use the `get()` method to retrieve my config, the keys that are returned only contain the default values and not the values for my conditions. 

It appears that this library is only setup to work with very basic Remote Config setups, and ignores "conditions" all together when reading the config.

**Comment by rvalitov** [comment]
Could it be related to my issue #3 ? In my case I also get only default value with `get()`.

**Comment by Inpassor** [comment]
Yes, this is a duplicate of issue #3
